export const handleError = (setError, setSuccess, errorMessage) => {
  setError(errorMessage);
  setSuccess("");
};
